import { Geist, Geist_Mono } from "next/font/google";
import SessionProvider from "@/app/components/SessionProvider";

// import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/AppSidebar";
import { AppTopbar } from "@/components/AppTopbar";
import { AppFooter } from "@/components/AppFooter"
;

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "FreeVibe",
  description: "Generated by create next app",
};

import { getServerSession } from "next-auth";
import { authOptions } from "@/app/api/auth/[...nextauth]/route";

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* สร้างไว้เผื่อใช้ เดะดูอีกทีควรใช้ตอนไหน */}
        {/* <SessionProvider session={session}> */}
          <SidebarProvider>
              <AppSidebar />
              <AppTopbar />
              <AppFooter />
              <main className="pt-14 pb-28 w-dvw px-5">
                  {children}
              </main>
          </SidebarProvider>
        {/* </SessionProvider> */}
      </body>
    </html>
  );
}
